# Generated by Django 4.2.3 on 2023-08-01 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
